### ISSUE TITLE
[BUG] Song is playing still it shows 'Nothing Playing'

### ISSUE THREAD

**Issue by Haider8** [SwagLyrics/SwagLyrics-For-Spotify#1133]
**To Reproduce**
1. Go to 'Spotify' and play song.
2. Go to terminal and type ```swaglyrics -t```
43. See error in the browser tab opened.

**Expected behavior**
Should have shown lyrics in the browser tab opened.

**Screenshots**
![spotify-swag-lyrics](https://user-images.githubusercontent.com/43299408/55393285-9a8f2200-555a-11e9-8f3d-778fcbb7e6cf.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Xubuntu 16.04]

**Comment by Haider8** [comment]
@aadibajpai Please confirm this

**Comment by aadibajpai** [comment]
Try playing/pausing a few times in Spotify.

**Comment by Haider8** [comment]
@aadibajpai Nothing happens, continously sending request to ```/songChanged``` but couldn't detect

**Comment by aadibajpai** [comment]
This happens with me rarely, try to rapidly play/pause until it flushes. It should work.

**Comment by aadibajpai** [comment]
Can you try again or so to confirm if this is a persistent issue or what?

**Comment by Haider8** [comment]
I have tried again, but doesn't help. Can this be a issue with dbus module.
Do i have to install it separately?

**Comment by aadibajpai** [comment]
Wait what, did you not install the dependencies?

**Comment by Haider8** [comment]
No. I thought it will be installed by the setup command.

**Comment by aadibajpai** [comment]
Did it? You must have seen the output?

**Comment by Haider8** [comment]
Can we add ```requirements.txt``` file? It will help to install the dependencies with just one command.

**Comment by aadibajpai** [comment]
Not sure what you're doing wrong. Install using pip then try.

**Comment by Haider8** [comment]
@aadibajpai I have checked all the dependencies thoroughly, but couldn't able to figure out the problem here. Amazing thing is, its not even showing me one error.

**Comment by aadibajpai** [comment]
Can you please uninstall it and do a simple pip or pipe install swaglyrics and then try it. Please post screenshots so I can see what's happening 🙂

**Comment by aadibajpai** [comment]
closing since no updates.

**Comment by Haider8** [comment]
@aadibajpai Sorry for replying so late was stuck with some college work. The project is working absolutely fine now. Is there any issue in this project which you have in mind. I will be happy to pick that up :)
