### ISSUE TITLE
I Can’t Get Enough (benny blanco, Selena Gomez, J Balvin, Tainy) by benny blanco unsupported.

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/SwagLyrics-For-Spotify#1393]
Check if issue with swaglyrics or whether song lyrics unavailable on Genius. 
<hr>
 <tt><b>stripper -> benny-blanco-I-Cant-Get-Enough-benny-blanco-Selena-Gomez-J-Balvin-Tainy</b>

version -> 0.2.6</tt>

**Comment by Haider8** [comment]
@aadibajpai This song is present on Genius [here](https://genius.com/Benny-blanco-tainy-selena-gomez-and-j-balvin-i-cant-get-enough-lyrics).

**Comment by aadibajpai** [comment]
added
