### ISSUE TITLE
[IMPROVEMENT] Add support for "ft." too for local files

### ISSUE THREAD

**Issue by laxyapahuja** [SwagLyrics/SwagLyrics-For-Spotify#1507]
As Spotify uses "feat." to show additional artists, SwagLyrics doesn't work for local files which have "ft." instead of "feat.".

Example:
![image](https://user-images.githubusercontent.com/31318248/60196912-e56bbd80-985b-11e9-9ac2-5d11e3cba122.png)

Here, it shows french lyrics fetched from https://genius.com/Genius-traductions-francaises-xxxtentacion-ice-hotel-ft-sza-traduction-francaise-lyrics when it should fetch it from https://genius.com/xxxtentacion-ice-hotel-lyrics

**Comment by aadibajpai** [comment]
Do you want to try and do it? It's an easy fix :)
