### ISSUE TITLE
Lovebites and Razorblades - 2009 Remaster by Glassjaw unsupported.

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/SwagLyrics-For-Spotify#1826]
Check if issue with swaglyrics or whether song lyrics unavailable on Genius. 
<hr>
 <tt><b>stripper -> Glassjaw-Lovebites-and-Razorblades</b>

version -> 1.1.0</tt>

**Comment by Aku-Akash** [comment]
The song lyrics is unavailable on genius. The lyrics for the older version of the song titled 'glassjaw-lovebites-and-razorlines' is available though.

**Comment by aadibajpai** [comment]
> The song lyrics is unavailable on genius. The lyrics for the older version of the song titled 'glassjaw-lovebites-and-razorlines' is available though.

Yeah, the issue management needs to be tidied up a little bit. We can't really do anything about this one so it should be deleted.
