### ISSUE TITLE
[BUG] Empty stripped song names get returned too

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/SwagLyrics-For-Spotify#1896]
**Describe the bug**

If a song name is say, fully in Japanese then we know that lyrics for it do not exist on Genius because of the Japanese characters. To that end, the stripper function completely removes the song name but the details are still passed ahead instead of being terminated right then. 

**To Reproduce**

1. Try SwagLyrics on some song like https://open.spotify.com/track/1U5lxCTM6ZR1mUu7GU91Zh?si=HQy3ahfwTcuQ0VKuhvcHxA (all non latin characters)
2. See SwagLyrics going through all the steps instead of terminating at the stripper, it would probably make an issue on github if you tried it

**Expected behavior**

The stripper function should see that since the song name is fully stripped it is not possible to get lyrics for that track and hence, get_lyrics should act accordingly. 

**Additional context**

In case you have further questions about this issue or have an idea for its solution, please feel free to reach out to me.

**Comment by sampoder** [comment]
I'll try to work on this later today!

**Comment by aadibajpai** [comment]
fixed with #2021
