### ISSUE TITLE
Ek Toh Kum Zindagani (From "Marjaavaan") by Neha Kakkar unsupported.

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/SwagLyrics-For-Spotify#2053]
Check if issue with swaglyrics or whether song lyrics unavailable on Genius. 
<hr>
 <tt><b>stripper -> Neha-Kakkar-Ek-Toh-Kum-Zindagani-From-Marjaavaan</b>

version -> 1.1.1</tt>

**Comment by vishal2612200** [comment]
This song is present on the genius website, I think, something is breaking inside the code.

**Comment by vishal2612200** [comment]
I had solve this bug, here is the proof in the coming time I will be sending you an pull request.
![Screenshot from 2020-02-15 10-34-32](https://user-images.githubusercontent.com/37480057/74582209-08133800-4fdf-11ea-9aa6-17d2c6d07f1e.png)

**Comment by vishal2612200** [comment]
I think we can close this issue now.
