### ISSUE TITLE
Ghungroo (From "War") by Arijit Singh unsupported.

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/SwagLyrics-For-Spotify#2055]
Check if issue with swaglyrics or whether song lyrics unavailable on Genius. 
<hr>
 <tt><b>stripper -> Arijit-Singh-Ghungroo-From-War</b>

version -> 1.1.1</tt>

**Comment by vishal2612200** [comment]
This issue is also solved on my system, here is the proof, we can close this issue also. 


![Screenshot from 2020-02-15 10-27-00](https://user-images.githubusercontent.com/37480057/74582268-ce8efc80-4fdf-11ea-9670-412c29e8d8af.png)
