### ISSUE TITLE
Sooraj Dooba Hain (From "Roy") by Arijit Singh unsupported.

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/SwagLyrics-For-Spotify#2070]
Check if issue with swaglyrics or whether song lyrics unavailable on Genius. 
<hr>
 <tt><b>stripper -> Arijit-Singh-Sooraj-Dooba-Hain-From-Roy</b>

version -> 1.1.1</tt>

**Comment by hv7214** [comment]
@aadibajpai I found it working. Please close this issue
