### ISSUE TITLE
Zikr (From "Amavas") by Armaan Malik unsupported.

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/SwagLyrics-For-Spotify#2093]
Check if issue with swaglyrics or whether song lyrics unavailable on Genius. 
<hr>
 <tt><b>stripper -> Armaan-Malik-Zikr-From-Amavas</b>

version -> 1.1.1</tt>

**Comment by chinmay021** [comment]
@aadibajpai the song lyrics is available on Genius-> https://genius.com/Armaan-malik-zikr-lyrics

**Comment by aadibajpai** [comment]
> @aadibajpai the song lyrics is available on Genius-> https://genius.com/Armaan-malik-zikr-lyrics

These will be fixed via a new release.

This issue tracks all of such songs #2090
