### ISSUE TITLE
Shaitan Ka Saala (From "Housefull 4") by Sohail Sen unsupported.

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/SwagLyrics-For-Spotify#2094]
Check if issue with swaglyrics or whether song lyrics unavailable on Genius. 
<hr>
 <tt><b>stripper -> Sohail-Sen-Shaitan-Ka-Saala-From-Housefull-4</b>

version -> 1.1.1</tt>

**Comment by vishal2612200** [comment]
Now this issue is also solved. 
![Screenshot from 2020-02-15 15-12-28](https://user-images.githubusercontent.com/37480057/74585705-add99d80-5005-11ea-851d-e3b2ca05e638.png)

We can close all the issue related to indian song.
