### ISSUE TITLE
[FEATURE] Add type hints

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/SwagLyrics-For-Spotify#2125]
**Is your feature request related to a problem? Please describe.**
Type hints are useful

**Describe the solution you'd like**
Add type hints

**Comment by flabbet** [comment]
What type hints? Please elaborate

**Comment by aadibajpai** [comment]
> What type hints? Please elaborate

https://docs.python.org/3/library/typing.html

**Comment by hv7214** [comment]
I guess most of the functions have typing defined except one or two. I will send the PR for same.

**Comment by aadibajpai** [comment]
done
