### ISSUE TITLE
[DOC] Missing development setup guide

### ISSUE THREAD

**Issue by hv7214** [SwagLyrics/SwagLyrics-For-Spotify#2147]
**Describe the bug**

There is no development setup guide for this project. So setting up is confusing for new comer.

**Expected behavior**

There should be a guide explaining how to setup this project.

**Comment by aadibajpai** [comment]
https://github.com/SwagLyrics/SwagLyrics-For-Spotify#compiling-swaglyrics-for-development

**Comment by hv7214** [comment]
@aadibajpai i think instructions are incomplete. Nothing is mentioned about starting the app.

**Comment by aadibajpai** [comment]
> @aadibajpai i think instructions are incomplete. Nothing is mentioned about starting the app.

https://github.com/SwagLyrics/SwagLyrics-For-Spotify#usage does this not work for you after compilation?

**Comment by hv7214** [comment]
@aadibajpai yeah did, Thanks! Closing this issue.
