### ISSUE TITLE
[BUG] Wrong instructions

### ISSUE THREAD

**Issue by hv7214** [SwagLyrics/SwagLyrics-For-Spotify#2148]
**Describe the bug**

 pip3 seems viable to install depedencies, as using pip throws error. 

**To Reproduce**
1. Follow steps given in README.md.
4. See error.

**Expected behavior**

Dependencies should have been installed by following instructions given in README.

**Error log**

`
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/harshit/SwagLyrics-For-Spotify/setup.py", line 5, in <module>
        with open("README.md", "r", encoding='utf8') as fh:
    TypeError: 'encoding' is an invalid keyword argument for this function`
**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by flabbet** [comment]
What Python version did you use?

**Comment by hv7214** [comment]
i have python2.7 and python3.6 installed in my system.

**Comment by flabbet** [comment]
This is a Python 2 error. SwagLyrics-For-Spotify doesn't support Python2.

**Comment by hv7214** [comment]
That's the point. Readme points to use pip

**Comment by hv7214** [comment]
That's the point. Readme points to use pip

**Comment by flabbet** [comment]
That's a good point, I think the reason is that on Windows there is no pre-installed Python, and after installing Python (which is usually Python 3+) `pip` points to Python3, but on Linux there is Python2 usually installed and therefore `pip` references to Python 2. I think this should be included in readme.

**Comment by hv7214** [comment]
yeah you got that right, should i mention this in README and send you PR for same ?

**Comment by flabbet** [comment]
Yeah, opening a PR is a good idea. I am not a maintainer, but @aadibajpai will check this.

**Comment by flabbet** [comment]
README already contains information about that, but you can improve it with example

**Comment by hv7214** [comment]
yeah sure

**Comment by aadibajpai** [comment]
![image](https://user-images.githubusercontent.com/27063113/74096393-64dc9300-4ab3-11ea-8254-ceff1a766c62.png)
It does say that you should use pip or pip3 depending on your installation 🙂

**Comment by hv7214** [comment]
@aadibajpai This issue is opened for *development setup* and that instruction is for installation of swaglyrics package, right?
