### ISSUE TITLE
[BUG] Displays wrong lyrics

### ISSUE THREAD

**Issue by hv7214** [SwagLyrics/SwagLyrics-For-Spotify#2156]
**Describe the bug**

Playing `Shallow by The Hound + The Fox` song displays `The Moon song by Karen O` song's lyrics.

**To Reproduce**
1. Go to Spotify.
2. Play `Shallow by The Hound + The Fox`.
3. See lyrics displayed by Swaglyrics.

**Expected behavior**

Since former song's lyrics doesn't exist on genius, it should have filed an issue on github.

**Screenshots**

![Screenshot from 2020-02-10 14-02-17](https://user-images.githubusercontent.com/42354803/74133187-0546ca80-4c0e-11ea-8e3c-ca46fdc38ff7.png)

**Desktop:**
 - OS: Ubuntu 18.04
 - Version: 1.2.0

**Comment by vishal2612200** [comment]
I think this issue is due to unavailable lyrics on the genius website, 
![Screenshot from 2020-02-15 15-23-14](https://user-images.githubusercontent.com/37480057/74585887-c6e34e00-5007-11ea-8a6a-fe5ab1afcfee.jpg)

**Comment by aadibajpai** [comment]
Yeah since lyrics aren't available the first time around, the backend tries to use the Genius API to try and resolve it. That's what the Genius API returned.
