### ISSUE TITLE
Death is inevitible

### ISSUE THREAD

**Issue by urmilshroff** [SwagLyrics/SwagLyrics-For-Spotify#2173]
Spotify on Android just started rolling out fully synced lyrics, and apparently it's beginning to show up on desktop too. [Source](https://twitter.com/keeperstattoo/status/1229806424315789313)

**Comment by aadibajpai** [comment]
Well even if they do integrate lyrics at some point, you'll still need to have the whole app open instead of just the terminal on the side.

**Comment by urmilshroff** [comment]
Yes, but do you think people will still prefer that over the official synced lyrics? Not to mention that people can resize the Spotify window as well. Just a thought

**Comment by flabbet** [comment]
Only time will show, but IMO SwagLyrics won't "die" in near future.

**Comment by urmilshroff** [comment]
> Only time will show, but IMO SwagLyrics won't "die" in near future.

I hope not. Don't get me wrong, I never meant it in a bad way. But I think people won't have the need to use Swaglyrics a few months after lyrics for desktop rolls out and becomes mature.

**Comment by aadibajpai** [comment]
So the thing is, yes, less people will use swaglyrics once there's official lyrics in the Spotify app. Once that happens, the advantages offered by swaglyrics will be niche. But I'm probably going to keep working it as long as even one person keeps using it or there's something I know which can be better. 

> Yes, but do you think people will still prefer that over the official synced lyrics? Not to mention that people can resize the Spotify window as well. Just a thought

Yeah but again, not all songs will have synced lyrics and I wonder if you can resize their window just so it contains the lyrics. Like I said, pretty niche but hopefully the person who's already accustomed to swaglyrics doesn't mind it.

Other than that, swaglyrics is definitely beyond this repo now. SwSpotify is pretty generalized, the discord bot is unique and autosynch is simply a work in cutting edge. So even if the value of this repo dies down, SwagLyrics as a project isn't going anywhere.

**Comment by aadibajpai** [comment]
Also the project is still useful as a library when you want to fetch specific lyrics programmatically 🤷‍♂
