### ISSUE TITLE
[BUG] Paused but playing?

### ISSUE THREAD

**Issue by bartekpacia** [SwagLyrics/SwagLyrics-For-Spotify#2385]
**Describe the bug**
It just happened randomly. I'm unable to provide any further information.

![demo](https://user-images.githubusercontent.com/40357511/84431225-3ae6d900-ac2b-11ea-9d70-57ced7cc26f6.gif)

**Expected behavior**
Should work?

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS Catalina 10.15.5

**Comment by aadibajpai** [comment]
does it persist or one off?

**Comment by aadibajpai** [comment]
It happens very rarely but generally play/pausing spotify fixes it.

**Comment by bartekpacia** [comment]
Apparently it was a one-off incident, started working just fine after some time.

**Comment by bartekpacia** [comment]
I just wanted to let you know that this exists, but if it's nothing very bad I'll close it.

**Comment by aadibajpai** [comment]
> I just wanted to let you know that this exists, but if it's nothing very bad I'll close it.

yeah it's just one of those things where we can't do anything about it
