### ISSUE TITLE
[BUG] Lyrics won't show up when using VPN

### ISSUE THREAD

**Issue by luthfisolahudin** [SwagLyrics/SwagLyrics-For-Spotify#2859]
**General description**

When I'm using VPN the lyrics won't show up. I'm also tested without a VPN connection, and the lyrics show up.

It shows an error, but I don't really know what that error means. And I think the error is not related to this problem because with or without a VPN connection, it still says the same error.

**Some screenshots**

+ Working, without VPN connected:

![Terminal output, working without VPN connected](https://user-images.githubusercontent.com/54571802/108790789-746f3280-7575-11eb-9866-122fd57ff0c2.png)
![Browser output, working without VPN connected](https://user-images.githubusercontent.com/54571802/108790801-7b964080-7575-11eb-9d07-26dcb47d9ef5.png)

+ With VPN connected:

![Terminal output, not working with VPN connected](https://user-images.githubusercontent.com/54571802/108791039-0e36df80-7576-11eb-990c-411e62de6264.png)
![Terminal output, not working with VPN connected](https://user-images.githubusercontent.com/54571802/108791042-0f680c80-7576-11eb-98ee-5e2738292c59.png)

**Currently, I'm using**

+ OS: Manjaro Linux
+ Version: 20.2.1 (latest update)

**Additional context**

The song that I used for testing is You (with Marshmello & Vance Joy) by benny blanco.

**Comment by luthfisolahudin** [comment]
Looks like the problem is on my VPN, not on the app.
Thank you.

**Comment by aadibajpai** [comment]
thanks! good to know
