### ISSUE TITLE
Two songs from Omega by Epica are not supported

### ISSUE THREAD

**Issue by airon90** [SwagLyrics/SwagLyrics-For-Spotify#2869]
* [x] [Kingdom of Heaven Prt. 3 - The Antediluvian Universe - ](https://open.spotify.com/track/2aIrU4sg9of8yLQvg0nZ1v) has its lyrics on Genius: [Epica-kingdom-of-heaven-part-3-the-antediluvian-universe](https://genius.com/Epica-kingdom-of-heaven-part-3-the-antediluvian-universe-lyrics)
* [x] [Synergize - Manic Manifest - ](https://open.spotify.com/track/0oxkVLOYr4E21MdyKaomqF) has its lyrics on Genius: [Epica-synergize-manic-manifest](https://genius.com/Epica-synergize-manic-manifest-lyrics)

**Comment by aadibajpai** [comment]
> * [x]  [Kingdom of Heaven Prt. 3 - The Antediluvian Universe - ](https://open.spotify.com/track/2aIrU4sg9of8yLQvg0nZ1v) has its lyrics on Genius: [Epica-kingdom-of-heaven-part-3-the-antediluvian-universe](https://genius.com/Epica-kingdom-of-heaven-part-3-the-antediluvian-universe-lyrics)
> * [x]  [Synergize - Manic Manifest - ](https://open.spotify.com/track/0oxkVLOYr4E21MdyKaomqF) has its lyrics on Genius: [Epica-synergize-manic-manifest](https://genius.com/Epica-synergize-manic-manifest-lyrics)

both of these should work now! let me know if it works
